# Generated by Django 6.0.4

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('produtor', models.CharField(max_length=200)),
                ('fazenda', models.CharField(max_length=200)),
                ('geojson', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REVISAO', 'Revisão'), ('BLOQUEADO', 'Bloqueado')], default='REVISAO', max_length=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('APROVADO', 'Aprovado'), ('SUSPEITO', 'Suspeito'), ('BLOQUEADO', 'Bloqueado')], default='SUSPEITO', max_length=10)),
                ('motivo', models.TextField(blank=True)),
                ('data_recepcao', models.DateTimeField(auto_now_add=True)),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='talhoes.talhao')),
            ],
        ),
    ]
