# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talhoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talhao',
            name='geojson',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
